# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CSb-uidi8L0HtdEIy2ogeL4W8dcik8Pk
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/supermarket_sales - Sheet1.csv")
print(df)

df.head()

print(pd.options.display.max_rows)

print(pd.options.display.max_columns)

print(df.isnull().sum())